language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

sudo: false

install:
  - python setup.py sdist
  - pip install dist/`python setup.py --name`-`python setup.py --version`.tar.gz
  - pip install -r test-requirements.txt

script:
  - PYTHONPATH=$PYTHONPATH:. mamba -s 0.0001

# PyPI deploy workaround based on: https://github.com/travis-ci/dpl/issues/299
before_deploy:
  - pip install twine

deploy:
  provider: pypi
  skip_cleanup: true
  user: jaimegildesagredo
  password:
    secure: KFU5K0be1VK6Chz5yXOIh+J5Fa+4QOw7T3qU599ex+EWHOuPFVShchxz8Z4+ChOwWfwS/erfY4J6xpj3rJZXhxu7BhcaQbFF2SBaI653kOol6N5rnpX63We4c1Sd7aNsqo5zURqlLe1TEM3n2zuob06+84K5r1dUcWcmzsKxBD4=
  on:
    tags: true
    repo: jaimegildesagredo/expects
    python: 3.4
